### ISSUE TITLE
Python OOP Exam 10 април,

### ISSUE THREAD

**Issue by ArifRasim** [Sheko1/SoftUni#1]
Здравей, Видях че реши успешно изпита на 10 Април ще може ли да качиш решението ,че изпускам нещо на Functuonality. Бях ти видял профила в някоя от лекциите и твоите решения ми помогнаха :D до сега. За това като видях че реши този изпит в контест резултса реших да ти пиша. Благодаря

**Comment by sibina-sto** [comment]
Здравейте, сега ги пиша :) обаче съм много бавно, съжалявам

**Comment by Sheko1** [comment]
https://github.com/Sheko1/SoftUni/tree/main/Python-OOP/Exam

На сб, 10.04.2021 г. в 19:31 ч. piziamko ***@***.***> написа:
